// <auto-generated />
using System;
using EFNpgsql_app.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFNpgsql_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250114101438_nowapostgres123")]
    partial class nowapostgres123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFNpgsql_app.Models.Drone", b =>
                {
                    b.Property<int>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DroneId"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("DroneId");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InsuranceId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InsuranceId");

                    b.HasIndex("PilotId")
                        .IsUnique();

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<int>("DroneId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationId");

                    b.HasIndex("DroneId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MissionId"));

                    b.Property<int>("DroneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MissionId");

                    b.HasIndex("DroneId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Pilot", b =>
                {
                    b.Property<int>("PilotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PilotId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PilotId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.PilotMission", b =>
                {
                    b.Property<int>("PilotId")
                        .HasColumnType("integer");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.HasKey("PilotId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("PilotMissions");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Insurance", b =>
                {
                    b.HasOne("EFNpgsql_app.Models.Pilot", "Pilot")
                        .WithOne("Insurance")
                        .HasForeignKey("EFNpgsql_app.Models.Insurance", "PilotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Location", b =>
                {
                    b.HasOne("EFNpgsql_app.Models.Drone", "Drone")
                        .WithMany("Locations")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Mission", b =>
                {
                    b.HasOne("EFNpgsql_app.Models.Drone", "Drone")
                        .WithMany("Missions")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.PilotMission", b =>
                {
                    b.HasOne("EFNpgsql_app.Models.Mission", "Mission")
                        .WithMany("PilotMissions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFNpgsql_app.Models.Pilot", "Pilot")
                        .WithMany("PilotMissions")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Drone", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Missions");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Mission", b =>
                {
                    b.Navigation("PilotMissions");
                });

            modelBuilder.Entity("EFNpgsql_app.Models.Pilot", b =>
                {
                    b.Navigation("Insurance");

                    b.Navigation("PilotMissions");
                });
#pragma warning restore 612, 618
        }
    }
}
